# Generated by Django 2.2.3 on 2019-07-02 23:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tvshow',
            old_name='seasons_number',
            new_name='seasons',
        ),
        migrations.RemoveField(
            model_name='tvshow',
            name='id',
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscription_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tvshow',
            name='poster_url',
            field=models.URLField(default='#'),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='imdb_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
