# Generated by Django 2.2.3 on 2019-07-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_auto_20190703_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvshow',
            name='genres',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='tvshow',
            name='year',
            field=models.CharField(default=None, max_length=4),
        ),
        migrations.AddField(
            model_name='tvshow',
            name='years',
            field=models.CharField(default=None, max_length=9),
        ),
    ]
